copyContents:
    "$rootDir/CommonFunctions":     "$buildPath/tools"
    "$rootDir/Conventions":     "$buildPath/tools"
    "$rootDir/Lib":     "$buildPath/tools"
    "$rootDir/YBuild":     "$buildPath/tools"
    "$rootDir/YScaffold":     "$buildPath/tools"
    "$rootDir/YScaffold":     "$buildPath/tools"
    "$rootDir/YDeliver.psm1":     "$buildPath/tools"

nugetSpecs:     [ydeliver.nuspec]